/**
 * =============================================================================
 * GPIO and RMW Hazard Demonstration Implementation
 * =============================================================================
 * Course: Embedded Systems Foundations — Phase 2 MCU Bare-Metal
 * Module: P2-M02 MMIO, Clock Tree, Hardware Timers, and NVIC Mechanism
 *
 * Mental Model & RMW Analysis:
 * 1. Non-atomic Read-Modify-Write (RMW):
 *      GPIOA->ODR ^= (1U << 2);
 *    Assembly generated by GCC:
 *      LDR  r1, [r0, #12]   ; 1. Read ODR register into CPU core register r1
 *      EOR  r1, r1, #4      ; 2. Modify bit 2 in core register
 *      STR  r1, [r0, #12]   ; 3. Write modified word back to ODR
 *
 *    If an interrupt (e.g. TIM2_IRQHandler) fires between step 1 and step 3
 *    and modifies another bit in GPIOA->ODR (e.g. pin 1), that write will be
 *    overwritten and lost when the thread returns and executes its STR!
 *
 * 2. Atomic Set / Reset Alternative (BSRR / BRR):
 *    STM32 GPIO hardware provides dedicated 32-bit registers:
 *      BSRR bits [15:0]  : Write 1 to set pin n
 *      BSRR bits [31:16] : Write 1 to reset pin n
 *      BRR  bits [15:0]  : Write 1 to reset pin n
 *    Each access is a single 32-bit store instruction (STR).
 *    No read cycle is required; hardware performs the set/reset atomically.
 * =============================================================================
 */

#include "gpio.h"
#include "stm32f103xb.h"

void gpio_init(void)
{
    /* 1. Enable GPIOA and GPIOC peripheral clocks in RCC (APB2 bus) */
    RCC->APB2ENR |= (RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPCEN);

    /* 2. Configure PA1 and PA2 as Output Push-Pull, max speed 10 MHz
     * Configuration bits in GPIOA->CRL:
     *   PA1: Bits [7:4]   -> CNF=00 (push-pull), MODE=01 (output 10 MHz) -> 0x1
     *   PA2: Bits [11:8]  -> CNF=00 (push-pull), MODE=01 (output 10 MHz) -> 0x1
     */
    GPIOA->CRL &= ~((0xFU << 4) | (0xFU << 8));
    GPIOA->CRL |=  ((0x1U << 4) | (0x1U << 8));

    /* 3. Configure PC13 as Output Push-Pull, max speed 2 MHz
     * Configuration bits in GPIOC->CRH:
     *   PC13: Bits [23:20] -> CNF=00, MODE=10 -> 0x2
     */
    GPIOC->CRH &= ~(0xFU << 20);
    GPIOC->CRH |=  (0x2U << 20);

    /* Ensure pins start in reset state */
    GPIOA->BRR = (1U << 1) | (1U << 2);
    GPIOC->BSRR = (1U << 13); /* PC13 LED off */
}

/* Software toggle state (single execution context).
 * Note: Hardware register writes (BSRR/BRR) are atomic at the peripheral bus level.
 * If toggle state were shared across preempting contexts, software tracking would
 * require additional critical section protection.
 */
static volatile uint32_t s_pa1_state = 0;

void gpio_toggle_pa1_atomic(void)
{
    if (s_pa1_state == 0) {
        GPIOA->BSRR = (1U << 1); /* Atomic hardware set PA1 without reading ODR */
        s_pa1_state = 1;
    } else {
        GPIOA->BRR  = (1U << 1); /* Atomic hardware reset PA1 without reading ODR */
        s_pa1_state = 0;
    }
}

void gpio_toggle_pa2_non_atomic_rmw(void)
{
    /* Non-atomic RMW hazard: compiles to LDR, EOR, STR */
    GPIOA->ODR ^= (1U << 2);
}

static volatile uint32_t s_pa2_state = 0;

void gpio_toggle_pa2_atomic(void)
{
    if (s_pa2_state == 0) {
        GPIOA->BSRR = (1U << 2);
        s_pa2_state = 1;
    } else {
        GPIOA->BRR  = (1U << 2);
        s_pa2_state = 0;
    }
}
